"""Add timestamp to transaction

Revision ID: dd76c39400e2
Revises: e40b953f6790
Create Date: 2022-01-29 17:54:42.754486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd76c39400e2'
down_revision = 'e40b953f6790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('uploaded', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'uploaded')
    # ### end Alembic commands ###
