"""Add timestamp to transaction

Revision ID: e8d831184214
Revises: dd76c39400e2
Create Date: 2022-01-29 17:59:31.594474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d831184214'
down_revision = 'dd76c39400e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('uploaded', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'uploaded')
    # ### end Alembic commands ###
